### ISSUE TITLE
probable typo in dtrace post

### ISSUE THREAD

**Issue by daveloyall** [skeeto/skeeto.github.com#4]
There is probably a typo around https://github.com/skeeto/skeeto.github.com/blame/33fe139e8d362e3b81b55593f5926c2dc2085070/_posts/2018-01-17-Debugging-Emacs-with-DTrace.markdown#L198-L210.  I say this because line L210 makes a back reference to `arg0`, but I wasn't able to find it.

**Comment by daveloyall** [comment]
Oh, at https://github.com/skeeto/skeeto.github.com/blame/33fe139e8d362e3b81b55593f5926c2dc2085070/_posts/2018-01-17-Debugging-Emacs-with-DTrace.markdown#L243, it becomes perfectly clear.

**Comment by skeeto** [comment]
This isn't an error: arg0 is present but unused for that probe. Consider 
the prototype for write(2):

    ssize_t write(int fd, const void *buf, size_t count);

arg0 corresponds to fd. Since this write will always go to standard 
output, fd is always 1 and so there's no reason to look at it. arg1 is 
buf, and arg2 is count, both of which are interesting in this case.

Would it be clearer if I put the write(2) prototype in the article?
